### PR TITLE
Update plugin interface to 2.0

### PR DESCRIPTION
**Pull request by urosgruber**
Plugin does not work with brunch v2 or newer. Please crate a new tag 2.0 after merge.

### CODE REVIEW

**Comment by urosgruber** [comment]
Any reason for this still opened?

**Comment by joshvillbrandt** [comment]
+1

**Comment by joshvillbrandt** [comment]
@huafu, thanks for merging this and tagging it as 2.0! Would you mind also pushing the 2.0 tag to npm??

**Comment by huafu** [comment]
done, sorry for all this delay but I have no time on any project since a while

**Pull request merged**
